use_frameworks!

platform :ios, '10.0'

target 'SwipeySearch_Example' do
  pod 'SwipeySearch', :path => '../'

  target 'SwipeySearch_Tests' do
    inherit! :search_paths

    post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
    end
    
  end
end
